### ISSUE TITLE
Doesn't work with astroid 2.0.0 (and thus Python 3.7)

### ISSUE THREAD

**Issue by hroncok** [rhinstaller/pocketlint#21]
Astroid 2.0.0 is the first astroid to support Python 3.7. Pocketlint doesn't work with it.

```
[pocketlint (master)]$ python3.6 -m venv __venv__
[pocketlint (master)]$ . __venv__/bin/activate
(__venv__) [pocketlint (master)]$ pip install --pre astroid pylint
...
Successfully installed astroid-2.0.0.dev1 isort-4.3.4 lazy-object-proxy-1.3.1 mccabe-0.6.1 pylint-2.0.0.dev1 six-1.11.0 typed-ast-1.1.0 wrapt-1.10.11
(__venv__) [pocketlint (master)]$ pip install -e.
...
Successfully installed pocketlint
(__venv__) [pocketlint (master %)]$ python tests/pylint/runpylint.py 
Traceback (most recent call last):
  File ".../pocketlint/__venv__/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File ".../pocketlint/__venv__/lib64/python3.6/site-packages/pylint/__init__.py", line 18, in run_pylint
    Run(sys.argv[1:])
  File ".../pocketlint/__venv__/lib64/python3.6/site-packages/pylint/lint.py", line 1292, in __init__
    linter.load_plugin_modules(self._plugins)
  File ".../pocketlint/__venv__/lib64/python3.6/site-packages/pylint/lint.py", line 501, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File ".../pocketlint/__venv__/lib64/python3.6/site-packages/astroid/modutils.py", line 190, in load_module_from_name
    return load_module_from_modpath(dotted_name.split('.'), path, use_sys)
  File ".../pocketlint/__venv__/lib64/python3.6/site-packages/astroid/modutils.py", line 233, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/usr/lib64/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../pocketlint/pocketlint/checkers/pointless-override.py", line 114, in <module>
    class PointlessFunctionDefinition(PointlessData):
  File ".../pocketlint/pocketlint/checkers/pointless-override.py", line 117, in PointlessFunctionDefinition
    _DEF_CLASS = astroid.Function
AttributeError: module 'astroid' has no attribute 'Function'
...
```

**Comment by hroncok** [comment]
Will send a PR.
